// AUTO-GENERATED by npm run sync:themes. Edit theme.json, NEVER edit this file.
import type { ArtThemeDefinition } from './artThemeSchema';
export const ART_THEMES = [
  {
    "schemaVersion": 1,
    "id": "inkdragon",
    "label": "水墨龙门",
    "title": "水墨龙门",
    "kicker": "INK DRAGON GATE",
    "subtitle": "一墨成鱼 · 跃门化龙",
    "highestLabel": "真龙化境",
    "icon": "🐉",
    "online": false,
    "ranks": {
      "2": "墨滴灵鱼",
      "4": "游墨小鱼",
      "8": "双尾墨鱼",
      "16": "白腹灵鲤",
      "32": "朱砂锦鲤",
      "64": "金纹龙鲤",
      "128": "墨角龙鲤",
      "256": "踏浪蛟",
      "512": "盘墨蛟龙",
      "1024": "腾云苍龙",
      "2048": "水墨真龙"
    },
    "assets": {
      "hero": "scene-hero.png",
      "board": "board-4x4.glb",
      "environmentMobile": "environment-mobile.glb",
      "tiles": {
        "2": "tiles/0002.glb",
        "4": "tiles/0004.glb",
        "8": "tiles/0008.glb",
        "16": "tiles/0016.glb",
        "32": "tiles/0032.glb",
        "64": "tiles/0064.glb",
        "128": "tiles/0128.glb",
        "256": "tiles/0256.glb",
        "512": "tiles/0512.glb",
        "1024": "tiles/1024.glb",
        "2048": "tiles/2048.glb"
      },
      "overlays": []
    },
    "placement": {
      "rows": 4,
      "columns": 4,
      "gridGap": 1.065,
      "artFloorY": 0.88,
      "gameSurfaceY": 0.695,
      "centerZ": 0
    },
    "camera": {
      "home": {
        "targetY": 0.74,
        "targetZOffset": -0.1,
        "distanceScale": 1.2,
        "eyeY": 0.9,
        "eyeZ": 0.58
      },
      "solo": {
        "targetY": 0.68,
        "targetZOffset": -0.04,
        "distanceScale": 1.12,
        "eyeY": 0.84,
        "eyeZ": 0.54
      }
    },
    "render": {
      "sky": "#DED2B8",
      "fog": "#D3C8B2",
      "exposure": 1.04,
      "accent": "#0B0D0E",
      "secondary": "#C62214",
      "spawn": "#F1E4C6",
      "skill": "#080A0B",
      "vfx": "ink",
      "confetti": [
        "#202526",
        "#A33B2D",
        "#A98945",
        "#E7DDC4"
      ]
    },
    "mood": {
      "preset": "generic",
      "thresholds": [
        2,
        16,
        64,
        256,
        1024
      ],
      "labels": [
        "晨雾初墨",
        "游鱼聚势",
        "龙门将启",
        "翻浪化蛟",
        "真龙现世"
      ],
      "glowMaterialKeys": {
        "gold": [
          "aged muted gold"
        ],
        "seal": [
          "vermilion cinnabar"
        ],
        "paper": [
          "warm rice paper",
          "cool rice paper"
        ]
      }
    }
  },
  {
    "schemaVersion": 1,
    "id": "nightmarket",
    "label": "东方夜市",
    "title": "东方夜市·莲灯盛会",
    "kicker": "ORIENTAL LANTERN FESTIVAL",
    "subtitle": "莲灯盛会 · 十一阶灵物",
    "highestLabel": "莲灯灵物",
    "icon": "🏮",
    "online": false,
    "ranks": {
      "2": "莲花团子",
      "4": "炭火狸猫",
      "8": "月灯玉兔",
      "16": "翡翠醒狮",
      "32": "琉璃锦鲤",
      "64": "紫晶魔女",
      "128": "玫瑰花妖",
      "256": "黄金招财蟾",
      "512": "冰晶凤凰",
      "1024": "月华九尾狐",
      "2048": "赤焰东方龙"
    },
    "assets": {
      "hero": "scene-hero.png",
      "board": "board-4x4.glb",
      "environmentMobile": "environment-mobile.glb",
      "environmentFull": "environment-nightmarket.glb",
      "tiles": {
        "2": "tiles/0002.glb",
        "4": "tiles/0004.glb",
        "8": "tiles/0008.glb",
        "16": "tiles/0016.glb",
        "32": "tiles/0032.glb",
        "64": "tiles/0064.glb",
        "128": "tiles/0128.glb",
        "256": "tiles/0256.glb",
        "512": "tiles/0512.glb",
        "1024": "tiles/1024.glb",
        "2048": "tiles/2048.glb"
      },
      "overlays": []
    },
    "placement": {
      "rows": 4,
      "columns": 4,
      "gridGap": 1.065,
      "artFloorY": 0.88,
      "gameSurfaceY": 0.695,
      "centerZ": 0
    },
    "camera": {
      "home": {
        "targetY": 0.76,
        "targetZOffset": -0.18,
        "distanceScale": 1.35,
        "eyeY": 0.88,
        "eyeZ": 0.64
      },
      "solo": {
        "targetY": 0.76,
        "targetZOffset": -0.18,
        "distanceScale": 1.24,
        "eyeY": 0.82,
        "eyeZ": 0.58
      }
    },
    "render": {
      "sky": "#232732",
      "fog": "#272b37",
      "exposure": 0.89,
      "accent": "#ffcf83",
      "secondary": "#83d6c6",
      "spawn": "#ffe0ac",
      "skill": "#e5b77b",
      "confetti": [
        "#ffcf83",
        "#e884a9",
        "#83d6c6",
        "#ffe6be",
        "#ee986a"
      ]
    },
    "mood": {
      "preset": "nightmarket",
      "thresholds": [
        2,
        16,
        64,
        256,
        1024
      ],
      "labels": [
        "初入夜市",
        "夜市苏醒",
        "夜市繁盛",
        "华彩高潮",
        "神灯盛会"
      ],
      "glowMaterialKeys": {
        "lantern": [
          "lantern golden illumination"
        ],
        "paper": [
          "warm ivory rice paper"
        ],
        "gold": [
          "aged imperial gilt",
          "burnished pale gold"
        ],
        "jade": [
          "celadon inset",
          "jade inset"
        ],
        "water": [
          "teal still water",
          "turquoise ripples"
        ],
        "lotus": [
          "lotus center glowing"
        ]
      }
    }
  }
] as const satisfies readonly ArtThemeDefinition[];
export type ArtThemeId = (typeof ART_THEMES)[number]['id'];
export const ART_THEME_BY_ID: Readonly<Record<string, ArtThemeDefinition>> =
  Object.fromEntries(ART_THEMES.map(item => [item.id, item]));
export function isArtTheme(id: string): id is ArtThemeId {
  return Object.prototype.hasOwnProperty.call(ART_THEME_BY_ID, id);
}
