import { randomUUID } from 'node:crypto';
import { mkdir, open, readFile, rename, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import {
  RELEASE_THEME_IDS,
  S_COIN_ECONOMY,
  THEME_UNLOCK_AD_DAILY_CAP,
  THEME_UNLOCK_ECONOMY,
  type MatchEndReason,
  type ReleaseThemeId,
} from '../../shared/index';

export const THEME_UNLOCK_COST = 500;
export const DAILY_LOGIN_S = S_COIN_ECONOMY.dailyLogin, DAILY_SIDEBAR_S = S_COIN_ECONOMY.sidebarReturn, DAILY_AD_S = S_COIN_ECONOMY.dailyRewardedAd, DAILY_TASK_S = S_COIN_ECONOMY.dailyTask, STREAK_CHEST_S = S_COIN_ECONOMY.sevenDayChest, DISCOVERY_S = S_COIN_ECONOMY.discoveryPerTier, MAX_DISCOVERY_TIER = 11, MAX_RECENT_AD_CLAIMS = 256, MAX_RECENT_MATCHES = 512, MAX_RECENT_GRANTS = 512, PVP_ELO_K = 24;
export interface ThemeDefinition { free:boolean; cost:number; adViews?:number }
export type ThemeRegistry = Readonly<Record<string, ThemeDefinition>>;
export const THEME_REGISTRY:ThemeRegistry = Object.fromEntries(
  RELEASE_THEME_IDS.map(id => [id, {
    free: THEME_UNLOCK_ECONOMY[id].free,
    cost: THEME_UNLOCK_ECONOMY[id].coinCost,
    adViews: THEME_UNLOCK_ECONOMY[id].adViewsRequired,
  }]),
);
const EPOCH = Date.parse('2026-01-01T00:00:00Z'), SEASON_MS = 14 * 86400000;
type Tasks = { solo: boolean; pvp: boolean; ad: boolean };
export interface Economy { balance:number; lifetimeEarned:number; lastDailyLoginDay?:string; lastDailyAdDay?:string; loginStreak:number; lastLoginDay?:string; sevenDayChestCycle:number; dailyTaskDay?:string; dailyTasks:Tasks; grants:string[]; discoveredTierByTheme:Record<string,number> }
export interface Season { seasonId:string; rating:number; wins:number; losses:number; draws:number; matches:number }
export interface PlayerAccount { id:string; douyinOpenId:string; unionId?:string; anonymousOpenId?:string; createdAt:number; updatedAt:number; profile:{displayName:string;avatarUrl?:string}; solo:{bestKingdom:number;highestKingdom:number;bestPalace:number;highestPalace:number}; soloByTheme:Record<string,{best:number;highest:number}>; pvp:{wins:number;losses:number;draws:number;rating:number}; rewards:{currency:number;lastSidebarRewardDay?:string}; adClaims:string[]; economy:Economy; themes:{owned:string[];trialDayByTheme:Record<string,string|undefined>;adUnlockProgress:Record<string,number>;themeAdDay?:string;themeAdViewsToday:number}; pvpSeason:Season }
export interface AccountMatchResult { matchId:string; reason:MatchEndReason; winnerId:string|null; players:readonly {playerId:string;accountId?:string}[] }
export interface SeasonInfo { id:string; startsAt:number; endsAt:number }
export interface LeaderboardEntry { rank:number; displayName:string; avatarUrl?:string; rating:number; wins:number; losses:number; draws:number; matches:number }
export type PublicPlayer = { id:string; displayName:string; avatarUrl?:string; solo:PlayerAccount['solo']; soloByTheme:PlayerAccount['soloByTheme']; pvp:PlayerAccount['pvp']; rewards:PlayerAccount['rewards'] & {daily:{day:string;loginClaimed:boolean;adClaimed:boolean;tasks:Tasks;streak:number}}; season:Season & {endsAt:number}; themes:{owned:string[];adUnlockProgress:Record<string,number>;adViewsToday:number;adDailyRemaining:number} };
export const utcDay=(now:number)=>new Date(now).toISOString().slice(0,10);
export function currentSeason(now:number):SeasonInfo { const n=Math.floor((now-EPOCH)/SEASON_MS), startsAt=EPOCH+n*SEASON_MS; return {id:`s${n}-${utcDay(startsAt)}`,startsAt,endsAt:startsAt+SEASON_MS}; }
const tier=(value:number)=>Math.min(MAX_DISCOVERY_TIER,Math.max(1,Math.floor(Math.log2(value))));
export const ownedThemes=(a:PlayerAccount,registry:ThemeRegistry=THEME_REGISTRY)=>[...new Set([...Object.entries(registry).filter(([, value])=>value.free).map(([id])=>id),...a.themes.owned])];
export function publicPlayer(a:PlayerAccount,now=Date.now()):PublicPlayer { const day=utcDay(now), s=currentSeason(now), tasks=a.economy.dailyTaskDay===day?{...a.economy.dailyTasks}:{solo:false,pvp:false,ad:false}; const adViewsToday=a.themes.themeAdDay===day?a.themes.themeAdViewsToday:0; return {id:a.id,displayName:a.profile.displayName,...(a.profile.avatarUrl?{avatarUrl:a.profile.avatarUrl}:{}),solo:{...a.solo},soloByTheme:structuredClone(a.soloByTheme),pvp:{...a.pvp},rewards:{...a.rewards,currency:a.economy.balance,daily:{day,loginClaimed:a.economy.lastDailyLoginDay===day,adClaimed:a.economy.lastDailyAdDay===day,tasks,streak:a.economy.loginStreak}},season:{...a.pvpSeason,endsAt:s.endsAt},themes:{owned:ownedThemes(a),adUnlockProgress:{...a.themes.adUnlockProgress},adViewsToday,adDailyRemaining:Math.max(0,THEME_UNLOCK_AD_DAILY_CAP-adViewsToday)}}; }
export interface AccountRepository {
 findById(id:string):Promise<PlayerAccount|null>; findOrCreate(openId:string,unionId?:string,anonymousOpenId?:string,now?:number):Promise<{account:PlayerAccount;created:boolean}>; updateProfile(id:string,displayName:string,avatarUrl:string|undefined,now?:number):Promise<PlayerAccount>;
 claimDailyLogin(id:string,now?:number):Promise<{account:PlayerAccount;granted:boolean;amount:number;streakAmount:number}>;
 claimSidebar(id:string,day:string,now?:number):Promise<{account:PlayerAccount;granted:boolean;amount:number}>;
 claimAd(id:string,kind:'solo_skill_refill'|'daily_s_coin',claimId:string,now?:number):Promise<{account:PlayerAccount;granted:boolean;amount:number;taskAmount:number}>;
 mergeSoloProgress(id:string,theme:ReleaseThemeId,best:number,highest:number,now?:number):Promise<{account:PlayerAccount;discoveryAmount:number;taskAmount:number}>;
 unlockTheme(id:string,themeId:string,requestId:string,now?:number):Promise<{account:PlayerAccount;unlocked:boolean;amount:number}>;
 unlockThemeByAd(id:string,themeId:string,claimId:string,now?:number):Promise<{account:PlayerAccount;granted:boolean;unlocked:boolean;limited:boolean;progress:number;required:number;dailyRemaining:number}>;
 recordMatch(result:AccountMatchResult,now?:number):Promise<boolean>; leaderboard(now?:number,limit?:number):Promise<{season:SeasonInfo;entries:LeaderboardEntry[]}>;
}
interface State { version:2; accounts:PlayerAccount[]; processedMatches:string[] }
const season=(now:number):Season=>({seasonId:currentSeason(now).id,rating:1000,wins:0,losses:0,draws:0,matches:0});
const initialSoloByTheme=(solo:PlayerAccount['solo']):PlayerAccount['soloByTheme']=>({
 kingdom:{best:solo.bestKingdom,highest:solo.highestKingdom},
 palace:{best:solo.bestPalace,highest:solo.highestPalace},
 zodiac:{best:0,highest:2}, candy:{best:0,highest:2}, dreamhouse:{best:0,highest:2},
});
const economy=(soloByTheme:PlayerAccount['soloByTheme']):Economy=>({balance:0,lifetimeEarned:0,loginStreak:0,sevenDayChestCycle:0,dailyTasks:{solo:false,pvp:false,ad:false},grants:[],discoveredTierByTheme:Object.fromEntries(Object.entries(soloByTheme).map(([id,progress])=>[id,tier(progress.highest)]))});
const guestDisplayName=(id:string)=>`玩家${(parseInt(id.replaceAll('-','').slice(0,8),16)%10000).toString().padStart(4,'0')}`;

export class JsonAccountRepository implements AccountRepository {
 private state:State={version:2,accounts:[],processedMatches:[]}; private pending:Promise<unknown>=Promise.resolve(); private constructor(private file:string,private readonly themeRegistry:ThemeRegistry){}
 static async open(file:string,options?:{themeRegistry?:ThemeRegistry}){const repo=new JsonAccountRepository(file,options?.themeRegistry??THEME_REGISTRY);try{const raw=JSON.parse(await readFile(file,'utf8')) as Partial<State>;if(!Array.isArray(raw.accounts))throw Error('unsupported account data format');repo.state=migrate(raw);if(raw.version!==2)await repo.persist();}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}return repo;}
 async findById(id:string){await this.pending;return this.state.accounts.find(a=>a.id===id)??null;}
 findOrCreate(openId:string,unionId?:string,anonymousOpenId?:string,now=Date.now()){return this.mutate(()=>{const a=this.state.accounts.find(x=>x.douyinOpenId===openId||!!(unionId&&x.unionId===unionId)||!!(anonymousOpenId&&(x.anonymousOpenId===anonymousOpenId||x.douyinOpenId===`anonymous:${anonymousOpenId}`)));if(a){let changed=roll(a,now);if(!openId.startsWith('anonymous:')&&a.douyinOpenId!==openId){a.douyinOpenId=openId;changed=true;}if(unionId&&a.unionId!==unionId){a.unionId=unionId;changed=true;}if(anonymousOpenId&&a.anonymousOpenId!==anonymousOpenId){a.anonymousOpenId=anonymousOpenId;changed=true;}if(changed)a.updatedAt=now;return {result:{account:a,created:false},changed};}const id=randomUUID(),solo={bestKingdom:0,highestKingdom:2,bestPalace:0,highestPalace:2},soloByTheme=initialSoloByTheme(solo);const account:PlayerAccount={id,douyinOpenId:openId,...(unionId?{unionId}:{}),...(anonymousOpenId?{anonymousOpenId}:{}),createdAt:now,updatedAt:now,profile:{displayName:guestDisplayName(id)},solo,soloByTheme,pvp:{wins:0,losses:0,draws:0,rating:1000},rewards:{currency:0},adClaims:[],economy:economy(soloByTheme),themes:{owned:[],trialDayByTheme:{},adUnlockProgress:{},themeAdViewsToday:0},pvpSeason:season(now)};this.state.accounts.push(account);return {result:{account,created:true},changed:true};});}
 updateProfile(id:string,displayName:string,avatarUrl:string|undefined,now=Date.now()){return this.mutate(()=>{const a=this.require(id),nextName=displayName.trim(),nextAvatar=avatarUrl===undefined?a.profile.avatarUrl:(avatarUrl.trim()||undefined),changed=a.profile.displayName!==nextName||a.profile.avatarUrl!==nextAvatar;if(changed){a.profile={displayName:nextName,...(nextAvatar?{avatarUrl:nextAvatar}:{})};a.updatedAt=now;}return {result:a,changed};});}
 claimDailyLogin(id:string,now=Date.now()){return this.mutate(()=>{const a=this.require(id),day=utcDay(now),rolled=roll(a,now);if(a.economy.lastDailyLoginDay===day)return {result:{account:a,granted:false,amount:0,streakAmount:0},changed:rolled};a.economy.loginStreak=a.economy.lastLoginDay===utcDay(now-86400000)?a.economy.loginStreak+1:1;a.economy.lastLoginDay=day;a.economy.lastDailyLoginDay=day;const amount=grant(a,`daily-login:${day}`,DAILY_LOGIN_S);let streakAmount=0;if(a.economy.loginStreak%7===0){a.economy.sevenDayChestCycle++;streakAmount=grant(a,`streak:cycle-${a.economy.sevenDayChestCycle}`,STREAK_CHEST_S);}a.updatedAt=now;return {result:{account:a,granted:true,amount,streakAmount},changed:true};});}
 claimSidebar(id:string,day:string,now=Date.now()){return this.mutate(()=>{const a=this.require(id),rolled=roll(a,now);if(a.rewards.lastSidebarRewardDay===day)return {result:{account:a,granted:false,amount:0},changed:rolled};a.rewards.lastSidebarRewardDay=day;const amount=grant(a,`sidebar:${day}`,DAILY_SIDEBAR_S);a.updatedAt=now;return {result:{account:a,granted:true,amount},changed:true};});}
 claimAd(id:string,kind:'solo_skill_refill'|'daily_s_coin',claimId:string,now=Date.now()){return this.mutate(()=>{const a=this.require(id),day=utcDay(now),rolled=roll(a,now);if(a.adClaims.includes(claimId)||(kind==='daily_s_coin'&&a.economy.lastDailyAdDay===day))return {result:{account:a,granted:false,amount:0,taskAmount:0},changed:rolled};a.adClaims.push(claimId);trim(a.adClaims,MAX_RECENT_AD_CLAIMS);let amount=0,taskAmount=0;if(kind==='daily_s_coin'){a.economy.lastDailyAdDay=day;amount=grant(a,`daily-ad:${day}`,DAILY_AD_S);taskAmount=task(a,'ad',day);}a.updatedAt=now;return {result:{account:a,granted:true,amount,taskAmount},changed:true};});}
 mergeSoloProgress(id:string,themeId:ReleaseThemeId,best:number,highest:number,now=Date.now()){return this.mutate(()=>{const a=this.require(id),day=utcDay(now);roll(a,now);const progress=a.soloByTheme[themeId]??{best:0,highest:2},before=tier(progress.highest);progress.best=Math.max(progress.best,best);progress.highest=Math.max(progress.highest,highest);a.soloByTheme[themeId]=progress;if(themeId==='kingdom'){a.solo.bestKingdom=progress.best;a.solo.highestKingdom=progress.highest;}else if(themeId==='palace'){a.solo.bestPalace=progress.best;a.solo.highestPalace=progress.highest;}const after=tier(progress.highest),known=a.economy.discoveredTierByTheme[themeId]??before;let discoveryAmount=0;for(let t=Math.max(before+1,known+1);t<=after;t++)discoveryAmount+=grant(a,`discovery:${themeId}:tier-${t}`,DISCOVERY_S);a.economy.discoveredTierByTheme[themeId]=Math.max(known,after);const taskAmount=task(a,'solo',day);a.updatedAt=now;return {result:{account:a,discoveryAmount,taskAmount},changed:true};});}
 unlockTheme(id:string,themeId:string,requestId:string,now=Date.now()){return this.mutate(()=>{const a=this.require(id),rolled=roll(a,now),definition=this.themeRegistry[themeId],grantKey=`theme:${themeId}:${requestId}`;if(!definition||!/^[A-Za-z0-9_-]{8,100}$/.test(requestId))throw Error('invalid_theme_request');if(ownedThemes(a,this.themeRegistry).includes(themeId))return {result:{account:a,unlocked:true,amount:0},changed:rolled};if(a.economy.grants.includes(grantKey))return {result:{account:a,unlocked:ownedThemes(a,this.themeRegistry).includes(themeId),amount:0},changed:rolled};if(a.economy.balance<definition.cost)return {result:{account:a,unlocked:false,amount:0},changed:rolled};a.economy.balance-=definition.cost;a.rewards.currency=a.economy.balance;a.themes.owned.push(themeId);remember(a.economy.grants,grantKey);a.updatedAt=now;return {result:{account:a,unlocked:true,amount:-definition.cost},changed:true};});}
 unlockThemeByAd(id:string,themeId:string,claimId:string,now=Date.now()){return this.mutate(()=>{const a=this.require(id),definition=this.themeRegistry[themeId],required=Math.max(0,Math.floor(definition?.adViews??0)),day=utcDay(now);if(!definition||!/^[A-Za-z0-9_-]{8,100}$/.test(claimId)||required<=0)throw Error('invalid_theme_ad_request');if(a.themes.themeAdDay!==day){a.themes.themeAdDay=day;a.themes.themeAdViewsToday=0;}const ownedNow=ownedThemes(a,this.themeRegistry).includes(themeId),dailyRemaining=()=>Math.max(0,THEME_UNLOCK_AD_DAILY_CAP-a.themes.themeAdViewsToday),progress=()=>Math.min(required,Math.max(0,a.themes.adUnlockProgress[themeId]??0));if(ownedNow)return {result:{account:a,granted:false,unlocked:true,limited:false,progress:required,required,dailyRemaining:dailyRemaining()},changed:false};if(a.adClaims.includes(claimId))return {result:{account:a,granted:false,unlocked:false,limited:false,progress:progress(),required,dailyRemaining:dailyRemaining()},changed:false};if(a.themes.themeAdViewsToday>=THEME_UNLOCK_AD_DAILY_CAP)return {result:{account:a,granted:false,unlocked:false,limited:true,progress:progress(),required,dailyRemaining:0},changed:false};a.adClaims.push(claimId);trim(a.adClaims,MAX_RECENT_AD_CLAIMS);a.themes.themeAdViewsToday++;a.themes.adUnlockProgress[themeId]=Math.min(required,progress()+1);const unlocked=a.themes.adUnlockProgress[themeId]>=required;if(unlocked&&!a.themes.owned.includes(themeId))a.themes.owned.push(themeId);a.updatedAt=now;return {result:{account:a,granted:true,unlocked,limited:false,progress:a.themes.adUnlockProgress[themeId],required,dailyRemaining:dailyRemaining()},changed:true};});}
 recordMatch(result:AccountMatchResult,now=Date.now()){return this.mutate(()=>{if(this.state.processedMatches.includes(result.matchId))return {result:false,changed:false};if(result.players.length!==2)throw Error('invalid match result');const accountIds=result.players.map(p=>p.accountId).filter((id):id is string=>Boolean(id));if(accountIds.length===0||new Set(accountIds).size!==accountIds.length)return {result:false,changed:false};const accounts=result.players.map(p=>p.accountId?this.state.accounts.find(a=>a.id===p.accountId)??null:null);for(const a of accounts)if(a)roll(a,now);const ratings=accounts.map(a=>a?.pvp.rating??1000),seasonRatings=accounts.map(a=>a?.pvpSeason.rating??1000),pair=accounts.every((a):a is PlayerAccount=>!!a);for(let i=0;i<2;i++){const a=accounts[i];if(!a)continue;const score=result.winnerId===null?.5:result.winnerId===result.players[i].playerId?1:0;outcome(a.pvp,score);if(pair){const e=1/(1+10**((ratings[1-i]-ratings[i])/400));a.pvp.rating=Math.max(0,ratings[i]+Math.round(PVP_ELO_K*(score-e)));outcome(a.pvpSeason,score);const se=1/(1+10**((seasonRatings[1-i]-seasonRatings[i])/400));a.pvpSeason.rating=Math.max(0,seasonRatings[i]+Math.round(PVP_ELO_K*(score-se)));}task(a,'pvp',utcDay(now));a.updatedAt=now;}this.state.processedMatches.push(result.matchId);trim(this.state.processedMatches,MAX_RECENT_MATCHES);return {result:true,changed:true};});}
 leaderboard(now=Date.now(),limit=50){return this.mutate(()=>{let changed=false;for(const a of this.state.accounts)changed=roll(a,now)||changed;const entries=[...this.state.accounts].filter(a=>a.pvpSeason.matches>0).sort((a,b)=>b.pvpSeason.rating-a.pvpSeason.rating||b.pvpSeason.matches-a.pvpSeason.matches||a.createdAt-b.createdAt||a.id.localeCompare(b.id)).slice(0,Math.min(50,Math.max(1,limit))).map((a,i)=>({rank:i+1,displayName:a.profile.displayName,...(a.profile.avatarUrl?{avatarUrl:a.profile.avatarUrl}:{}),rating:a.pvpSeason.rating,wins:a.pvpSeason.wins,losses:a.pvpSeason.losses,draws:a.pvpSeason.draws,matches:a.pvpSeason.matches}));return {result:{season:currentSeason(now),entries},changed};});}
 private require(id:string){const a=this.state.accounts.find(x=>x.id===id);if(!a)throw Error('account missing');return a;}
 private mutate<T>(fn:()=>{result:T;changed:boolean}):Promise<T>{const op=this.pending.then(async()=>{const before=structuredClone(this.state);try{const x=fn();if(x.changed)await this.persist();return x.result;}catch(e){this.state=before;throw e;}});this.pending=op.catch(()=>undefined);return op;}
 private async persist(){const dir=dirname(this.file),tmp=join(dir,`.accounts-${randomUUID()}.tmp`);await mkdir(dir,{recursive:true,mode:0o700});try{const h=await open(tmp,'wx',0o600);try{await h.writeFile(JSON.stringify(this.state));await h.sync();}finally{await h.close();}await rename(tmp,this.file);if(process.platform!=='win32'){const h=await open(dir,'r');try{await h.sync();}finally{await h.close();}}}finally{await rm(tmp,{force:true});}}
}
function roll(a:PlayerAccount,now:number){const id=currentSeason(now).id;if(a.pvpSeason.seasonId===id)return false;a.pvpSeason={...season(now),rating:Math.round(1000+(a.pvpSeason.rating-1000)*.25)};a.updatedAt=now;return true;}
function grant(a:PlayerAccount,key:string,amount:number){if(a.economy.grants.includes(key))return 0;remember(a.economy.grants,key);a.economy.balance+=amount;a.economy.lifetimeEarned+=amount;a.rewards.currency=a.economy.balance;return amount;}
function task(a:PlayerAccount,key:keyof Tasks,day:string){if(a.economy.dailyTaskDay!==day){a.economy.dailyTaskDay=day;a.economy.dailyTasks={solo:false,pvp:false,ad:false};}if(a.economy.dailyTasks[key])return 0;a.economy.dailyTasks[key]=true;return grant(a,`task:${key}:${day}`,DAILY_TASK_S);}
function outcome(a:{wins:number;losses:number;draws:number;matches?:number},score:number){if(score===1)a.wins++;else if(score===0)a.losses++;else a.draws++;if('matches'in a)a.matches = (a.matches ?? 0) + 1;}
function remember(a:string[],x:string){a.push(x);trim(a,MAX_RECENT_GRANTS);} function trim(a:string[],n:number){if(a.length>n)a.splice(0,a.length-n);}
function migrate(raw:Partial<State>):State{const accounts=(raw.accounts??[]) as PlayerAccount[];for(const a of accounts){a.profile??={displayName:guestDisplayName(a.id)};a.profile.displayName=typeof a.profile.displayName==='string'&&a.profile.displayName.trim()?a.profile.displayName.trim():guestDisplayName(a.id);if(/^玩家[0-9A-Fa-f]{4}$/.test(a.profile.displayName)&&/[A-Fa-f]/.test(a.profile.displayName))a.profile.displayName=guestDisplayName(a.id);if(a.profile.avatarUrl!==undefined&&typeof a.profile.avatarUrl!=='string')delete a.profile.avatarUrl;a.adClaims=Array.isArray(a.adClaims)?a.adClaims.slice(-MAX_RECENT_AD_CLAIMS):[];a.soloByTheme??=initialSoloByTheme(a.solo);for(const themeId of RELEASE_THEME_IDS)a.soloByTheme[themeId]??={best:0,highest:2};a.soloByTheme.kingdom={best:Math.max(a.soloByTheme.kingdom.best,a.solo.bestKingdom),highest:Math.max(a.soloByTheme.kingdom.highest,a.solo.highestKingdom)};a.soloByTheme.palace={best:Math.max(a.soloByTheme.palace.best,a.solo.bestPalace),highest:Math.max(a.soloByTheme.palace.highest,a.solo.highestPalace)};a.solo.bestKingdom=a.soloByTheme.kingdom.best;a.solo.highestKingdom=a.soloByTheme.kingdom.highest;a.solo.bestPalace=a.soloByTheme.palace.best;a.solo.highestPalace=a.soloByTheme.palace.highest;const legacyEconomy=!a.economy;a.economy??=economy(a.soloByTheme);if(legacyEconomy)a.economy.balance=a.rewards.currency??0;a.economy.grants??=[];a.economy.dailyTasks??={solo:false,pvp:false,ad:false};a.economy.discoveredTierByTheme??={};for(const themeId of RELEASE_THEME_IDS)a.economy.discoveredTierByTheme[themeId]??=tier(a.soloByTheme[themeId]?.highest??2);a.economy.balance??=a.rewards.currency??0;a.economy.lifetimeEarned??=a.economy.balance;a.economy.loginStreak??=0;a.economy.sevenDayChestCycle??=0;a.rewards.currency=a.economy.balance;a.themes??={owned:[],trialDayByTheme:{},adUnlockProgress:{},themeAdViewsToday:0};a.themes.owned??=[];a.themes.trialDayByTheme??={};a.themes.adUnlockProgress??={};a.themes.themeAdViewsToday??=0;for(const themeId of RELEASE_THEME_IDS){const progress=a.soloByTheme[themeId];if(!THEME_UNLOCK_ECONOMY[themeId].free&&(progress?.best>0||(progress?.highest??2)>2)&&!a.themes.owned.includes(themeId))a.themes.owned.push(themeId);}a.pvpSeason??=season(a.updatedAt||Date.now());}return {version:2,accounts,processedMatches:Array.isArray(raw.processedMatches)?raw.processedMatches.slice(-MAX_RECENT_MATCHES):[]};}
